name: DevPulse Activity Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: python -m pip install --upgrade pip
    - run: pip install pytz

    - run: python commit.py

    - run: |
        git config user.name "Shubham Dangade"
        git config user.email "shubhamdangade01@gmail.com"
        git add .
        git commit -m "Auto commit by DevPulse AI" || echo "No changes"
        git push
